import { ToastProvider } from '@radix-ui/react-toast'
import '../globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from '@/components/toaster'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function StartLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider swipeDirection="right">
        <Toaster />
        <div className="h-screen">
          
          <div className="bg-white  ">
            {children}  
          </div>
        </div>
        </ToastProvider>
      </body>
    </html>
  )
}
